------------
insert into store (store_id, open_time, close_time, name, street, city) values (1, '8:16', '21:24', 'White Group', 'David', 'Wielbark');
insert into store (store_id, open_time, close_time, name, street, city) values (2, '8:54', '21:08', 'Witting, Nicolas and Veum', 'Hagan', 'Krasnokholm');
insert into store (store_id, open_time, close_time, name, street, city) values (3, '8:04', '20:57', 'Maggio, Sauer and Quitzon', 'Sunbrook', 'Sidi Smaïl');
insert into store (store_id, open_time, close_time, name, street, city) values (4, '9:33', '21:27', 'Abernathy and Sons', 'Macpherson', 'Bene ''Ayish');
insert into store (store_id, open_time, close_time, name, street, city) values (5, '7:35', '20:52', 'Gulgowski, Mraz and Koss', 'Hoffman', 'Sant Cugat Del Valles');
insert into store (store_id, open_time, close_time, name, street, city) values (6, '7:27', '21:10', 'Luettgen-Rogahn', 'Heath', 'Lindi');
insert into store (store_id, open_time, close_time, name, street, city) values (7, '7:49', '20:00', 'Volkman, Gutmann and Wolf', 'Messerschmidt', 'Zhaixi');
insert into store (store_id, open_time, close_time, name, street, city) values (8, '8:21', '21:32', 'Kozey-Schamberger', 'Mifflin', 'Inkerman');
insert into store (store_id, open_time, close_time, name, street, city) values (9, '8:47', '21:49', 'Kertzmann Group', 'Vermont', 'Heung-hai');
insert into store (store_id, open_time, close_time, name, street, city) values (10, '8:55', '22:45', 'Kirlin-Bechtelar', 'Hoard', 'Saint-Étienne');
insert into store (store_id, open_time, close_time, name, street, city) values (11, '8:19', '20:22', 'Hauck, Collier and Ortiz', 'Stephen', 'Lugang');
insert into store (store_id, open_time, close_time, name, street, city) values (12, '7:38', '20:02', 'Witting-Boyer', 'Johnson', 'Casillas');
insert into store (store_id, open_time, close_time, name, street, city) values (13, '8:16', '22:46', 'Ferry-Bauch', 'Jana', 'Bulgan');
insert into store (store_id, open_time, close_time, name, street, city) values (14, '7:20', '20:26', 'Powlowski, Kutch and Ziemann', 'Spaight', 'Tanahwulan');
insert into store (store_id, open_time, close_time, name, street, city) values (15, '8:19', '20:04', 'Nitzsche, Abernathy and Abbott', 'Hermina', 'San Pascual');
insert into store (store_id, open_time, close_time, name, street, city) values (16, '7:18', '21:04', 'Cronin-Wisozk', 'Independence', 'Italó');
insert into store (store_id, open_time, close_time, name, street, city) values (17, '9:27', '21:48', 'Dickinson, Schiller and Auer', 'Dwight', 'Makrýgialos');
insert into store (store_id, open_time, close_time, name, street, city) values (18, '8:35', '21:35', 'Schamberger, Stokes and Koelpin', 'Dwight', 'Itamaraju');
insert into store (store_id, open_time, close_time, name, street, city) values (19, '8:33', '22:00', 'Berge-Rolfson', 'Knutson', 'Hecun');
insert into store (store_id, open_time, close_time, name, street, city) values (20, '8:59', '22:03', 'Hills-Marks', 'Sherman', 'Mabalacat');
insert into store (store_id, open_time, close_time, name, street, city) values (21, '9:36', '22:32', 'Mann-Bartell', 'Granby', 'Dorotea');
insert into store (store_id, open_time, close_time, name, street, city) values (22, '7:29', '22:15', 'Schmidt Group', 'Kim', 'Safakulevo');
insert into store (store_id, open_time, close_time, name, street, city) values (23, '9:01', '21:49', 'Schuster-Fritsch', 'Florence', 'Travesía');
insert into store (store_id, open_time, close_time, name, street, city) values (24, '9:43', '20:53', 'O''Hara, Considine and Casper', 'Old Gate', 'Bagikkedok Lauk');
insert into store (store_id, open_time, close_time, name, street, city) values (25, '9:47', '21:05', 'Bogan-Lesch', 'Tennyson', 'Kawangu Satu');
------------
insert into vendor (v_id, first_name, last_name) values (1, 'Bond', 'Melley');
insert into vendor (v_id, first_name, last_name) values (2, 'Tonie', 'Gatland');
insert into vendor (v_id, first_name, last_name) values (3, 'Isis', 'Ertelt');
insert into vendor (v_id, first_name, last_name) values (4, 'Myriam', 'Albany');
insert into vendor (v_id, first_name, last_name) values (5, 'Wheeler', 'Janicijevic');
insert into vendor (v_id, first_name, last_name) values (6, 'Oliviero', 'Morhall');
insert into vendor (v_id, first_name, last_name) values (7, 'Adan', 'Gath');
insert into vendor (v_id, first_name, last_name) values (8, 'Saudra', 'Wethers');
insert into vendor (v_id, first_name, last_name) values (9, 'Twila', 'Moston');
insert into vendor (v_id, first_name, last_name) values (10, 'Breena', 'Curnock');
insert into vendor (v_id, first_name, last_name) values (11, 'Cointon', 'Spellecy');
insert into vendor (v_id, first_name, last_name) values (12, 'Meir', 'Sawle');
insert into vendor (v_id, first_name, last_name) values (13, 'Rhetta', 'Sibthorp');
insert into vendor (v_id, first_name, last_name) values (14, 'Archie', 'Coats');
insert into vendor (v_id, first_name, last_name) values (15, 'Julianne', 'Carren');
insert into vendor (v_id, first_name, last_name) values (16, 'Evvie', 'Paule');
insert into vendor (v_id, first_name, last_name) values (17, 'Dorice', 'Chessor');
insert into vendor (v_id, first_name, last_name) values (18, 'Dennison', 'State');
insert into vendor (v_id, first_name, last_name) values (19, 'Mirna', 'Finby');
insert into vendor (v_id, first_name, last_name) values (20, 'Sancho', 'Wrennall');
insert into vendor (v_id, first_name, last_name) values (21, 'Judy', 'Neesham');
insert into vendor (v_id, first_name, last_name) values (22, 'Cesare', 'Jaszczak');
insert into vendor (v_id, first_name, last_name) values (23, 'Christoph', 'Cauldwell');
insert into vendor (v_id, first_name, last_name) values (24, 'Melody', 'Janney');
insert into vendor (v_id, first_name, last_name) values (25, 'Kingston', 'Watkins');
------------
insert into v_phone_number (phone_id, phone) values (1, '657-451-3932');
insert into v_phone_number (phone_id, phone) values (2, '381-448-4335');
insert into v_phone_number (phone_id, phone) values (3, '515-517-7557');
insert into v_phone_number (phone_id, phone) values (4, '527-920-3267');
insert into v_phone_number (phone_id, phone) values (5, '994-676-8570');
insert into v_phone_number (phone_id, phone) values (6, '932-912-2604');
insert into v_phone_number (phone_id, phone) values (7, '620-452-1960');
insert into v_phone_number (phone_id, phone) values (8, '521-739-6404');
insert into v_phone_number (phone_id, phone) values (9, '793-831-4388');
insert into v_phone_number (phone_id, phone) values (10, '180-887-8081');
insert into v_phone_number (phone_id, phone) values (11, '569-725-1339');
insert into v_phone_number (phone_id, phone) values (12, '511-706-9251');
insert into v_phone_number (phone_id, phone) values (13, '350-864-8399');
insert into v_phone_number (phone_id, phone) values (14, '560-531-6261');
insert into v_phone_number (phone_id, phone) values (15, '658-496-7044');
insert into v_phone_number (phone_id, phone) values (16, '794-853-0139');
insert into v_phone_number (phone_id, phone) values (17, '150-261-9202');
insert into v_phone_number (phone_id, phone) values (18, '345-697-3215');
insert into v_phone_number (phone_id, phone) values (19, '647-543-8714');
insert into v_phone_number (phone_id, phone) values (20, '222-916-0098');
insert into v_phone_number (phone_id, phone) values (21, '165-325-4806');
insert into v_phone_number (phone_id, phone) values (22, '124-596-3828');
insert into v_phone_number (phone_id, phone) values (23, '183-712-7825');
insert into v_phone_number (phone_id, phone) values (24, '952-318-5956');
insert into v_phone_number (phone_id, phone) values (25, '341-825-0042');
------------
insert into brand (brand_id, name) values (1, 'Sanford, Klocko and Schroeder');
insert into brand (brand_id, name) values (2, 'Waelchi Inc');
insert into brand (brand_id, name) values (3, 'Feest and Sons');
insert into brand (brand_id, name) values (4, 'Grant-Roberts');
insert into brand (brand_id, name) values (5, 'Baumbach, Lind and Kuvalis');
insert into brand (brand_id, name) values (6, 'Braun, Macejkovic and Zulauf');
insert into brand (brand_id, name) values (7, 'Hudson, Goodwin and McGlynn');
insert into brand (brand_id, name) values (8, 'Smith, Brakus and Skiles');
insert into brand (brand_id, name) values (9, 'Tillman, Gulgowski and Block');
insert into brand (brand_id, name) values (10, 'Zemlak Inc');
insert into brand (brand_id, name) values (11, 'Ward Inc');
insert into brand (brand_id, name) values (12, 'Dietrich, Bailey and Leffler');
insert into brand (brand_id, name) values (13, 'Breitenberg-Wisoky');
insert into brand (brand_id, name) values (14, 'Mann, Cummerata and Ward');
insert into brand (brand_id, name) values (15, 'Windler Group');
insert into brand (brand_id, name) values (16, 'Wiegand and Sons');
insert into brand (brand_id, name) values (17, 'Casper-Goodwin');
insert into brand (brand_id, name) values (18, 'Davis, Mraz and Collins');
insert into brand (brand_id, name) values (19, 'Predovic-Hansen');
insert into brand (brand_id, name) values (20, 'Ondricka-Schulist');
insert into brand (brand_id, name) values (21, 'Champlin-Larkin');
insert into brand (brand_id, name) values (22, 'Labadie-Will');
insert into brand (brand_id, name) values (23, 'Hyatt and Sons');
insert into brand (brand_id, name) values (24, 'Denesik, Runolfsdottir and Leffler');
insert into brand (brand_id, name) values (25, 'Abshire-Smith');
------------
insert into orders (order_id, date, amount) values (1, '2021-08-21', 10);
insert into orders (order_id, date, amount) values (2, '2021-10-18', 3);
insert into orders (order_id, date, amount) values (3, '2021-08-20', 2);
insert into orders (order_id, date, amount) values (4, '2021-06-03', 2);
insert into orders (order_id, date, amount) values (5, '2021-11-17', 10);
insert into orders (order_id, date, amount) values (6, '2021-05-23', 9);
insert into orders (order_id, date, amount) values (7, '2021-11-13', 3);
insert into orders (order_id, date, amount) values (8, '2021-06-08', 8);
insert into orders (order_id, date, amount) values (9, '2021-06-13', 8);
insert into orders (order_id, date, amount) values (10, '2021-03-26', 8);
insert into orders (order_id, date, amount) values (11, '2021-02-25', 8);
insert into orders (order_id, date, amount) values (12, '2021-04-29', 3);
insert into orders (order_id, date, amount) values (13, '2021-01-06', 7);
insert into orders (order_id, date, amount) values (14, '2021-02-04', 2);
insert into orders (order_id, date, amount) values (15, '2021-06-17', 9);
insert into orders (order_id, date, amount) values (16, '2021-07-28', 8);
insert into orders (order_id, date, amount) values (17, '2020-12-14', 9);
insert into orders (order_id, date, amount) values (18, '2021-05-12', 6);
insert into orders (order_id, date, amount) values (19, '2021-01-24', 8);
insert into orders (order_id, date, amount) values (20, '2021-02-23', 6);
insert into orders (order_id, date, amount) values (21, '2021-04-26', 9);
insert into orders (order_id, date, amount) values (22, '2021-09-04', 5);
insert into orders (order_id, date, amount) values (23, '2021-10-25', 10);
insert into orders (order_id, date, amount) values (24, '2020-12-04', 10);
insert into orders (order_id, date, amount) values (25, '2021-08-03', 8);
------------
insert into customer (c_id, last_name, first_name) values (1, 'Ivison', 'Gayler');
insert into customer (c_id, last_name, first_name) values (2, 'Bigley', 'Coriss');
insert into customer (c_id, last_name, first_name) values (3, 'Blaydes', 'Bonny');
insert into customer (c_id, last_name, first_name) values (4, 'Lademann', 'Clio');
insert into customer (c_id, last_name, first_name) values (5, 'Rulton', 'Rafa');
insert into customer (c_id, last_name, first_name) values (6, 'Spincks', 'Florencia');
insert into customer (c_id, last_name, first_name) values (7, 'Perrottet', 'Tove');
insert into customer (c_id, last_name, first_name) values (8, 'Stonner', 'Claudine');
insert into customer (c_id, last_name, first_name) values (9, 'Hincks', 'Anselma');
insert into customer (c_id, last_name, first_name) values (10, 'Wadie', 'Glynis');
insert into customer (c_id, last_name, first_name) values (11, 'Spurrett', 'Madalyn');
insert into customer (c_id, last_name, first_name) values (12, 'Pennoni', 'Gilligan');
insert into customer (c_id, last_name, first_name) values (13, 'Toomer', 'Aldus');
insert into customer (c_id, last_name, first_name) values (14, 'Watchorn', 'Doyle');
insert into customer (c_id, last_name, first_name) values (15, 'Spriddle', 'Freddie');
insert into customer (c_id, last_name, first_name) values (16, 'Mewis', 'Thatcher');
insert into customer (c_id, last_name, first_name) values (17, 'Willard', 'Karon');
insert into customer (c_id, last_name, first_name) values (18, 'Saile', 'Anneliese');
insert into customer (c_id, last_name, first_name) values (19, 'Colt', 'Cammy');
insert into customer (c_id, last_name, first_name) values (20, 'Skeats', 'Jared');
insert into customer (c_id, last_name, first_name) values (21, 'Gingle', 'Babbie');
insert into customer (c_id, last_name, first_name) values (22, 'Preble', 'Mickey');
insert into customer (c_id, last_name, first_name) values (23, 'Drinkel', 'Veronique');
insert into customer (c_id, last_name, first_name) values (24, 'Dudeney', 'Zak');
insert into customer (c_id, last_name, first_name) values (25, 'Folds', 'Ellissa');
------------
insert into account (user_name, password) values ('kibanez0', 'QwxpqsIJ3ZFs');
insert into account (user_name, password) values ('jmoxted1', '7r7C2xE');
insert into account (user_name, password) values ('emallison2', 'XyMpVVottca');
insert into account (user_name, password) values ('cmongeot3', '1AwHWzvvh');
insert into account (user_name, password) values ('tpinnell4', '9r0Vxf3');
insert into account (user_name, password) values ('vdoole5', 'xi3ZCRrH');
insert into account (user_name, password) values ('akingescot6', 'BWMhLsNP8x');
insert into account (user_name, password) values ('ofronsek7', 'OmZ5PobSac');
insert into account (user_name, password) values ('trubenfeld8', '0F24K8Y');
insert into account (user_name, password) values ('jsones9', '5J3qR383h4P');
insert into account (user_name, password) values ('abielefelda', 'x4qwvTn3iKrT');
insert into account (user_name, password) values ('eerlamb', '2ZvirZT');
insert into account (user_name, password) values ('istapyltonc', 'qsvQUViEJ5');
insert into account (user_name, password) values ('binggalld', 'efJ2MoIt8ka');
insert into account (user_name, password) values ('tgoldfinche', '0YxDFy6oPHP');
insert into account (user_name, password) values ('ldudgeonf', 'tp8nAKA8');
insert into account (user_name, password) values ('lnultyg', '1I6JaFuB3aH');
insert into account (user_name, password) values ('tosanh', 'YbQ2EcvC7');
insert into account (user_name, password) values ('dhryniewickii', 'tNyyifi9');
insert into account (user_name, password) values ('bblanshardj', 'FJoDMzwbvrb');
insert into account (user_name, password) values ('halyoshink', 'EbI2lrXQOf');
insert into account (user_name, password) values ('lgawthropl', 'Es4CPYwTYYk');
insert into account (user_name, password) values ('mchilverm', '6jzlTbdM0c');
insert into account (user_name, password) values ('lenrightn', 'jx4r29TlklT');
insert into account (user_name, password) values ('edeschelleo', 'xL1aDhZ2');
------------
insert into c_phone_number (phone_id, phone) values (1, '886-393-3324');
insert into c_phone_number (phone_id, phone) values (2, '391-129-7832');
insert into c_phone_number (phone_id, phone) values (3, '964-129-8416');
insert into c_phone_number (phone_id, phone) values (4, '593-849-0767');
insert into c_phone_number (phone_id, phone) values (5, '944-704-7319');
insert into c_phone_number (phone_id, phone) values (6, '381-541-0650');
insert into c_phone_number (phone_id, phone) values (7, '621-341-6919');
insert into c_phone_number (phone_id, phone) values (8, '364-872-6525');
insert into c_phone_number (phone_id, phone) values (9, '271-432-8050');
insert into c_phone_number (phone_id, phone) values (10, '381-100-9507');
insert into c_phone_number (phone_id, phone) values (11, '651-999-0747');
insert into c_phone_number (phone_id, phone) values (12, '917-995-9425');
insert into c_phone_number (phone_id, phone) values (13, '861-857-8053');
insert into c_phone_number (phone_id, phone) values (14, '435-108-9923');
insert into c_phone_number (phone_id, phone) values (15, '718-204-0713');
insert into c_phone_number (phone_id, phone) values (16, '605-968-9138');
insert into c_phone_number (phone_id, phone) values (17, '268-156-8137');
insert into c_phone_number (phone_id, phone) values (18, '500-845-1228');
insert into c_phone_number (phone_id, phone) values (19, '763-396-0480');
insert into c_phone_number (phone_id, phone) values (20, '571-799-8721');
insert into c_phone_number (phone_id, phone) values (21, '536-565-0047');
insert into c_phone_number (phone_id, phone) values (22, '764-215-5104');
insert into c_phone_number (phone_id, phone) values (23, '417-227-8359');
insert into c_phone_number (phone_id, phone) values (24, '315-423-5326');
insert into c_phone_number (phone_id, phone) values (25, '206-439-9432');
------------
insert into c_address (address_id, address) values (1, '5 Walton Lane');
insert into c_address (address_id, address) values (2, '1 Paget Way');
insert into c_address (address_id, address) values (3, '8 Dwight Crossing');
insert into c_address (address_id, address) values (4, '19626 Kinsman Street');
insert into c_address (address_id, address) values (5, '74 Cambridge Way');
insert into c_address (address_id, address) values (6, '29 Stone Corner Junction');
insert into c_address (address_id, address) values (7, '52 Oak Court');
insert into c_address (address_id, address) values (8, '13977 Sutherland Park');
insert into c_address (address_id, address) values (9, '59605 Thompson Way');
insert into c_address (address_id, address) values (10, '48398 8th Park');
insert into c_address (address_id, address) values (11, '60 Debs Drive');
insert into c_address (address_id, address) values (12, '7 Badeau Junction');
insert into c_address (address_id, address) values (13, '786 Alpine Pass');
insert into c_address (address_id, address) values (14, '6 Twin Pines Terrace');
insert into c_address (address_id, address) values (15, '91758 Old Shore Parkway');
insert into c_address (address_id, address) values (16, '8 Lyons Street');
insert into c_address (address_id, address) values (17, '93 Summerview Drive');
insert into c_address (address_id, address) values (18, '79 Manufacturers Pass');
insert into c_address (address_id, address) values (19, '35 Autumn Leaf Pass');
insert into c_address (address_id, address) values (20, '206 Brentwood Pass');
insert into c_address (address_id, address) values (21, '90 Calypso Road');
insert into c_address (address_id, address) values (22, '9 Vidon Crossing');
insert into c_address (address_id, address) values (23, '4877 Packers Terrace');
insert into c_address (address_id, address) values (24, '76178 Main Trail');
insert into c_address (address_id, address) values (25, '3 Bultman Terrace');
------------
insert into descriptions (description_id, description) values (1, 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque');
insert into descriptions (description_id, description) values (2, 'pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis');
insert into descriptions (description_id, description) values (3, 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper');
insert into descriptions (description_id, description) values (4, 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit');
insert into descriptions (description_id, description) values (5, 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem');
insert into descriptions (description_id, description) values (6, 'platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec');
insert into descriptions (description_id, description) values (7, 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo');
insert into descriptions (description_id, description) values (8, 'nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque');
insert into descriptions (description_id, description) values (9, 'pede lobortis ligula sit amet eleifend pede libero quis orci');
insert into descriptions (description_id, description) values (10, 'sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam');
insert into descriptions (description_id, description) values (11, 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam');
insert into descriptions (description_id, description) values (12, 'ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit');
insert into descriptions (description_id, description) values (13, 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam');
insert into descriptions (description_id, description) values (14, 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam');
insert into descriptions (description_id, description) values (15, 'enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est');
insert into descriptions (description_id, description) values (16, 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum');
insert into descriptions (description_id, description) values (17, 'urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium');
insert into descriptions (description_id, description) values (18, 'aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero');
insert into descriptions (description_id, description) values (19, 'sit amet lobortis sapien sapien non mi integer ac neque');
insert into descriptions (description_id, description) values (20, 'cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non');
insert into descriptions (description_id, description) values (21, 'et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient');
insert into descriptions (description_id, description) values (22, 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate');
insert into descriptions (description_id, description) values (23, 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices');
insert into descriptions (description_id, description) values (24, 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus');
insert into descriptions (description_id, description) values (25, 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu');
------------
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('9543448485', 27212, 'Squeeze Bottle', 87, '2021-11-22', 'pede lobortis', 7);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('8497647432', 23077, 'Veal - Kidney', 74, '2021-09-17', 'sed tristique', 7);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('4455720774', 26748, 'Saskatoon Berries - Frozen', 16, '2021-10-18', 'felis', 8);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('7794262437', 21951, 'Crackers - Trio', 36, '2021-08-30', 'vel', 7);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('5357478945', 30208, 'Bread - Flat Bread', 51, '2021-05-12', 'praesent', 4);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('3280313856', 24740, 'Wine - Ej Gallo Sonoma', 85, '2021-07-05', 'vel', 8);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('5790030564', 10156, 'Dish Towel', 99, '2021-01-04', 'nunc', 1);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('3480249736', 49653, 'Soup Campbells - Italian Wedding', 92, '2021-10-30', 'blandit lacinia', 5);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('1027277004', 1623, 'Cheese - Parmesan Cubes', 55, '2021-09-01', 'non sodales', 3);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('1786915278', 15701, 'Flower - Dish Garden', 68, '2021-05-03', 'morbi', 3);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('6728392718', 22159, 'French Pastry - Mini Chocolate', 23, '2021-12-03', 'aliquet', 1);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('1810861179', 36858, 'Pastry - Apple Muffins - Mini', 16, '2021-06-08', 'pellentesque', 5);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('8918176279', 11685, 'Juice - Happy Planet', 47, '2021-10-21', 'lacus', 9);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('2547079909', 32898, 'Lobster - Baby, Boiled', 19, '2021-02-18', 'scelerisque mauris', 7);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('7947443521', 48835, 'Corn - Mini', 65, '2021-04-21', 'hac habitasse', 8);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('4833396254', 3640, 'Beer - Upper Canada Lager', 1, '2021-02-04', 'at lorem', 5);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('8842274712', 8498, 'Chocolate - Sugar Free Semi Choc', 33, '2021-05-10', 'accumsan', 8);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('3799060464', 15005, 'Sprouts - Bean', 9, '2021-09-10', 'dictumst', 3);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('4378438151', 24361, 'Guinea Fowl', 31, '2021-05-24', 'congue vivamus', 4);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('4009282355', 8221, 'Sugar - Individual Portions', 2, '2021-08-20', 'vitae', 6);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('0054547083', 5517, 'Sauce - Demi Glace', 36, '2021-05-24', 'mauris laoreet', 6);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('2004394986', 47587, 'Yams', 73, '2021-01-10', 'pretium iaculis', 5);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('6310555812', 49380, 'Table Cloth 90x90 Colour', 97, '2021-07-07', 'faucibus accumsan', 9);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('3908256976', 48223, 'Cocktail Napkin Blue', 23, '2021-08-11', 'ornare', 3);
insert into products (UPC_code, price, name, p_amount, arrival, packaging , size) values ('5765022960', 22042, 'Mushroom - Morels, Dry', 31, '2021-03-13', 'est', 9);
